### ISSUE TITLE
WTF is this? xD

### ISSUE THREAD

**Issue by prajjwaldimri** [VjRawat/Study#1]
Completing some new year's resolution of making a new repo every day?

**Comment by VjRawat** [comment]
This is nothing XD

**Comment by VjRawat** [comment]
XDXDyeah nice resolution :P

**Comment by prajjwaldimri** [comment]
:walking_man:

**Comment by VjRawat** [comment]
nice issue by the way XD

**Comment by prajjwaldimri** [comment]
bc har din meri feed pe new repo ki notifications aa rahi to kya karun xD

**Comment by VjRawat** [comment]
shi hai na update milra hai ki mai pollution mai v jinda hun XD

**Comment by prajjwaldimri** [comment]
xD haram ye chatroom nahi hai. chalo issue ko vanakkam \_/\\\_
